package constants

const (
	API_KEY_PREFIX     = "ak_"
	API_KEY_PREFIX_LEN = 8
)

var ASSIGNABLE_API_KEY_PERMISSIONS = []string{
	PERMISSION_ORG_READ,

	PERMISSION_MEMBERS_READ,
	PERMISSION_MEMBERS_WRITE,

	PERMISSION_TEAM_READ,
	PERMISSION_TEAM_WRITE,

	PERMISSION_TEAM_MEMBER_READ,
	PERMISSION_TEAM_MEMBER_WRITE,
}
