package constants

const (
	FEATURE_API_ACCESS = "api_access"
	FEATURE_AUDIT_LOG  = "audit_log"
	FEATURE_TEAMS      = "teams"
	FEATURE_ROLES      = "roles"
)

var FEATURES_FOR_PLANS = map[string][]string{
	FEATURE_API_ACCESS: {TIER_PRO, TIER_ENTERPRISE},
	FEATURE_AUDIT_LOG:  {TIER_BASIC, TIER_PRO, TIER_ENTERPRISE},
	FEATURE_TEAMS:      {TIER_PRO, TIER_ENTERPRISE},
	FEATURE_ROLES:      {TIER_BASIC, TIER_PRO, TIER_ENTERPRISE},
}
